
import { PersonaTemplate, TranslationStrings, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  ko: {
    nav_home: "홈",
    nav_forge: "AI 전문가 만들기",
    nav_market: "전문가 마켓",
    nav_store: "충전소",
    nav_auth: "로그인",
    nav_logout: "로그아웃",
    title: "PersonaForge",
    subtitle: "당신을 돕기 위해 기다리는 AI 전문가 팀을 만나보세요.",
    roleLabel: "누가 당신을 도와드리면 좋을까요?",
    roleHint: "예: 입시 전략가, 친절한 요리 선생님, 전문 세무사",
    expertiseLabel: "어떤 지식이 꼭 필요한가요?",
    expertiseHint: "전문가가 알고 있어야 할 핵심 정보나 배경을 적어주세요.",
    toneLabel: "대화 스타일",
    toneHint: "친구처럼 친근하게, 혹은 뉴스 앵커처럼 정확하게 중 골라주세요.",
    constraintsLabel: "상담 규칙",
    constraintsHint: "전문가가 답변할 때 꼭 지켜야 할 약속이나 주의사항이 있나요?",
    generateBtn: "전문가 AI 생성 (-10 토큰)",
    generating: "전문가 지식을 AI에 입히는 중...",
    resultTitle: "AI 전문가 세팅 완료",
    startChatBtn: "전문가와 대화하기",
    chatPlaceholder: "메시지를 보내보세요...",
    historyTitle: "나의 상담 기록",
    credits: "보유 포인트",
    refill: "포인트 충전",
    buyTokens: "포인트 요금제",
    insufficientTokens: "포인트가 부족해요! 충전소에서 충전해주세요.",
    expertBadge: "인증된 전문가",
    unlockExpert: "전문가 지식 고용하기",
    recentActivity: "최근 상담",
    expertMarketplace: "전문가 마켓플레이스",
    viewAll: "전체보기",
    login: "로그인",
    signup: "회원가입",
    email: "이메일 주소",
    password: "비밀번호",
    name: "이름",
    checkout: "결제하기",
    cardNumber: "카드 번호",
    expiry: "유효 기간 (MM/YY)",
    cvc: "CVC",
    payNow: "지금 결제하기",
    paymentSuccess: "결제가 완료되었습니다!",
    processing: "결제 처리 중...",
    guestMsg: "전문가 기능을 사용하려면 로그인이 필요합니다."
  },
  en: {
    nav_home: "Home",
    nav_forge: "Build Expert",
    nav_market: "Hire Experts",
    nav_store: "Points",
    nav_auth: "Login",
    nav_logout: "Logout",
    title: "PersonaForge",
    subtitle: "Hire or build the perfect AI expert for any task.",
    roleLabel: "Who are you looking for?",
    roleHint: "e.g., Senior Career Coach, Expert Chef, Tax Attorney",
    expertiseLabel: "What knowledge do they need?",
    expertiseHint: "Describe the core skills or background they must have.",
    toneLabel: "Conversation Style",
    toneHint: "Friendly like a friend, or precise like a scientist?",
    constraintsLabel: "Expert Guidelines",
    constraintsHint: "Are there any specific rules the AI must follow?",
    generateBtn: "Build Expert AI (-10 Tokens)",
    generating: "Training your expert AI...",
    resultTitle: "Expert Persona Ready",
    startChatBtn: "Start Consulting",
    chatPlaceholder: "Ask anything...",
    historyTitle: "My Consultations",
    credits: "Points",
    refill: "Get Points",
    buyTokens: "Select Points Plan",
    insufficientTokens: "Out of points! Please refill to continue.",
    expertBadge: "Verified Expert",
    unlockExpert: "Hire Expert Knowledge",
    recentActivity: "Recent Activity",
    expertMarketplace: "Expert Marketplace",
    viewAll: "See All",
    login: "Log In",
    signup: "Sign Up",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    checkout: "Secure Checkout",
    cardNumber: "Card Number",
    expiry: "Expiry Date (MM/YY)",
    cvc: "CVC",
    payNow: "Complete Purchase",
    paymentSuccess: "Payment Successful!",
    processing: "Processing Transaction...",
    guestMsg: "Please login to access expert features."
  },
  ja: {
    nav_home: "ホーム",
    nav_forge: "AIを作る",
    nav_market: "マーケット",
    nav_store: "チャージ",
    nav_auth: "ログイン",
    nav_logout: "ログアウト",
    title: "PersonaForge",
    subtitle: "あなたを助けるAI専門家チームに出会いましょう。",
    roleLabel: "どのような専門家が必要ですか？",
    roleHint: "例：進路アドバイザー、プロの料理人、公인会計士",
    expertiseLabel: "どのような知識が必要ですか？",
    expertiseHint: "専門家が知っておくべき核心情報を入力してください。",
    toneLabel: "会話スタイル",
    toneHint: "友達のように親密に、あるいは論理的で冷静になど。",
    constraintsLabel: "相談ルール",
    constraintsHint: "回答時に必ず守るべき約束や注意点はありますか？",
    generateBtn: "専門家AIを作成 (-10 トークン)",
    generating: "AIをトレーニング中...",
    resultTitle: "AI専門家の設定完了",
    startChatBtn: "相談を開始する",
    chatPlaceholder: "何でも聞いてください...",
    historyTitle: "相談履歴",
    credits: "ポイント",
    refill: "ポイントを購入",
    buyTokens: "ポイントプラン",
    insufficientTokens: "ポイントが不足しています。チャージしてください。",
    expertBadge: "公認専門家",
    unlockExpert: "専門家を雇用する",
    recentActivity: "最近の相談",
    expertMarketplace: "専門家マーケット",
    viewAll: "すべて見る",
    login: "ログイン",
    signup: "新規登録",
    email: "メールアドレス",
    password: "パスワード",
    name: "名前",
    checkout: "安全な決済",
    cardNumber: "カード番号",
    expiry: "有効期限 (MM/YY)",
    cvc: "CVC",
    payNow: "今すぐ支払う",
    paymentSuccess: "決済が完了しました！",
    processing: "決済処理中...",
    guestMsg: "専門家機能を利用するにはログインが必要です。"
  }
};

export const TEMPLATES: PersonaTemplate[] = [
  {
    id: 'basic-assistant',
    title: { ko: '스마트 비서', en: 'Smart Assistant', ja: 'スマート秘書' },
    description: { ko: '일정 관리와 일상 질문을 척척 해결합니다.', en: 'Handles scheduling and daily questions.', ja: 'スケジュール管理や日常의 질문을 해결。' },
    config: { role: 'Smart Productivity Assistant', tone: 'Kind, Efficient, Direct', expertise: 'Time Management, Life Hacks' },
    category: 'Life'
  }
];

export const EXPERT_TEMPLATES: PersonaTemplate[] = [
  {
    id: 'expert-startup-mentor',
    title: { ko: '유니콘 스타트업 멘토', en: 'Unicorn Startup Mentor', ja: 'ユニコーン創業メンター' },
    description: { ko: '투자 유치부터 팀 빌딩까지의 노하우.', en: 'Know-how from fundraising to team building.', ja: '資金調達からチームビルディングまで。' },
    config: { role: 'Serial Entrepreneur & Mentor', tone: 'Bold, Strategic, Insightful', expertise: 'Pitching, Unit Economics, Scaling' },
    isExpert: true,
    creator: 'Alex Rivera (Ex-Google)',
    tokenCost: 50,
    category: 'Business'
  },
  {
    id: 'expert-mental-health',
    title: { ko: '마음건강 심리 상담사', en: 'Compassionate Therapist', ja: '心の健康カウンセラー' },
    description: { ko: '따뜻한 공감과 과학적 기반의 상담.', en: 'Empathetic and evidence-based therapy.', ja: '温かい共感と科学的根拠に基づく相談。' },
    config: { role: 'Licensed Clinical Psychologist', tone: 'Warm, Listening, Patient', expertise: 'CBT, Anxiety Management, Mindfulness' },
    isExpert: true,
    creator: 'Dr. Sarah Kim',
    tokenCost: 70,
    category: 'Health'
  },
  {
    id: 'expert-code-architect',
    title: { ko: '시니어 시스템 아키텍트', en: 'Senior Systems Architect', ja: 'シニアアーキテクト' },
    description: { ko: '복잡한 설계 문제를 명쾌하게 풀어냅니다.', en: 'Solves complex design problems clearly.', ja: '複雑な設計問題を明快に解決。' },
    config: { role: 'Principal Software Engineer', tone: 'Technical, Methodical, Professional', expertise: 'Distributed Systems, Cloud Infrastructure' },
    isExpert: true,
    creator: 'David Chen',
    tokenCost: 80,
    category: 'Tech'
  }
];
